## plot the ROC curve for classification of y with p
roc <- function(p,y,p2,y2,p3,y3,p4,y4, ...){
  y <- factor(y)
  y2 <- factor(y2)
  y3 <- factor(y3)
  y4 <- factor(y4)
  n <- length(p)
  p <- as.vector(p)
  p2 <- as.vector(p2)
  p3 <- as.vector(p3)
  p4 <- as.vector(p4)
  Q <- p > matrix(rep(seq(0,1,length=100),n),ncol=100,byrow=TRUE)
  specificity <- colMeans(!Q[y==levels(y)[1],])
  sensitivity <- colMeans(Q[y==levels(y)[2],])
  Q2 <- p2 > matrix(rep(seq(0,1,length=100),n),ncol=100,byrow=TRUE)
  specificity2 <- colMeans(!Q2[y2==levels(y2)[1],])
  sensitivity2 <- colMeans(Q2[y2==levels(y2)[2],])
  Q3 <- p3 > matrix(rep(seq(0,1,length=100),n),ncol=100,byrow=TRUE)
  specificity3 <- colMeans(!Q3[y3==levels(y3)[1],])
  sensitivity3 <- colMeans(Q3[y3==levels(y3)[2],])
  Q4 <- p4 > matrix(rep(seq(0,1,length=100),n),ncol=100,byrow=TRUE)
  specificity4 <- colMeans(!Q4[y4==levels(y4)[1],])
  sensitivity4 <- colMeans(Q4[y4==levels(y4)[2],])
  plot(1-specificity, sensitivity, type="l", ...)
  lines(1-specificity2, sensitivity2, type="l", col="2", ...)
  lines(1-specificity3, sensitivity3, type="l", col="3", ...)
  lines(1-specificity4, sensitivity4, type="l", col="4", ...)
  abline(a=0,b=1,lty=2,col=8)
}

